### ISSUE TITLE
Conflicting options are not indicated in any way

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/swarm-cli#104]
Example:

`swarm-cli feed print --help`

```
█ Required Options:

-i --identity   Name of the identity                                             [string]
-a --address    Public Ethereum Address for feed lookup                          [string]
```

However, in practice, either `identity` or `address` is required. This is enforced runtime by the parser, but help should indicate this as well.

---

I would print an extra line at the end of the categories (in this case Required Options):

```
█ Required Options:

-i --identity   Name of the identity                                             [string]
-a --address    Public Ethereum Address for feed lookup                          [string]

Mutually exclusive: [identity] and [address]
```

Maybe that's jargon, so `Only one is required: [identity] or [address]` or `Exactly one must be specified: [identity] or [address]` are better choices.

**Comment by Cafe137** [comment]
@agazso what do you think is a good wording here?

**Comment by agazso** [comment]
I agree with the original being jargon.

I like the `Only one is required` but the other alternative is fine too.
