### ISSUE TITLE
Failed to run command!

### ISSUE THREAD

**Issue by JuXinCheng** [ethersphere/swarm-cli#118]
amd3900@amd3900-System-Product-Name:~$swarm-cli stamp buy --amount 1 --depth 20

error
 Failed to run command!

Bad Request

????????????????????

**Comment by JuXinCheng** [comment]
ubuntu 20.04

**Comment by Cafe137** [comment]
Hello @JuXinCheng,

Sorry to see you are having trouble running the command.

The real error message is unfortunately not available in `swarm-cli` right now.

I suggest you to run `curl -X POST http://localhost:1633/stamps/1/20` to get the full response, including why the request is 400 Bad Request.

Let me know if I can help further.

I will close the issue once error messages are properly printed in `swarm-cli` too.
