### ISSUE TITLE
Bee compatibility check

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/swarm-cli#124]
I propose a simple command, `swarm-cli check` which does the following:

- Checks if Bee API is available
- Checks if Bee Debug API is available
- - Checks health
- - Checks compatibility
- - Prints Bee version

Should be very easy, these are all implemented in `bee-js`.

**Comment by Cafe137** [comment]
@agazso Do you approve?

**Comment by agazso** [comment]
Yes, but maybe with a different command name, because it's too similar to the already existing `cheque` command. How about `status`?

**Comment by Cafe137** [comment]
Good point. 🙂
