### ISSUE TITLE
Allow empty strings for arguments

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/swarm-cli#134]
For `pss`, an empty string is a valid `target` value. Currently the parser does not allow it. We need a property to `allowEmptyStrings`.

**Comment by agazso** [comment]
How about making the `target` optional instead of required argument?

**Comment by Cafe137** [comment]
@agazso I feel like it conveys a different meaning.

Also, my assumption is that it would be used mainly without a target then, which to my understanding, is an unreliable way of sending PSS messages.

Not strong opinions - if you think these are not valid, or acceptable risks, then let's do it as you suggest.

**Comment by Cafe137** [comment]
Empty target no longer seems to be a valid value
