### ISSUE TITLE
 swarm-cli stamp buy --amount ：always waiting

### ISSUE THREAD

**Issue by lulei0215** [ethersphere/swarm-cli#136]
swarm-cli stamp buy --amount 10000000 --depth 20 --gas-price 10000000000000
⠇ Buying postage stamp. This may take a while.
⠹ Buying postage stamp. This may take a while.
⠇ Buying postage stamp. This may take a while
always waiting

**Comment by Cafe137** [comment]
Hello @lulei0215,

This is probably because the testnet is congested.

You can try increasing the gas price even further. It may also succeed after giving it more time.

I also recommend keeping an eye on the Bee log to see if you notice anything unusual about the postage stamp creation.

**Comment by Cafe137** [comment]
@lulei0215 Can I provide further help from `swarm-cli` side? Since this is an issue with the current testnet state, I propose to close this issue otherwise.
