### ISSUE TITLE
PSS topic is handled incorrectly

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#141]
It seems that in Bee the [topic is defined differently](https://github.com/ethersphere/bee/issues/2041) for the PSS and the Feed APIs.

In a nutshell, the feed APIs expect the topic as a hex string (so basically hex encoded arbitrary binary data) whereas the PSS APIs expect it to be a string. The PSS API then take the passed in string and hashes it with keccak256 internally to create the 32 bytes internal topic.

However we implemented a similar convenience functionality for feeds and we reused it for the PSS, therefore if you pass in a topic as a string it will be hashed twice. This may not cause a problem if both the sender and the receiver is using swarm-cli, however this will not work as expected if either the sender or the receiver is using something else (e.g. curl).

**Comment by Cafe137** [comment]
This was fixed as part of #144
