### ISSUE TITLE
Exit code is always zero with `status` command

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#154]
When I run the status command and it fails for some reason it returns `0` error code (which indicates no error). It would be better if it were returning non-zero error code. This happens both in silent mode (`-s`) and normal mode.

Example:
```
% swarm-cli status -q
FAILED - Bee API Connection
FAILED - Bee Debug API Connection
FAILED - Bee Version Compatibility
Bee version - N/A
Supported version - 0.6.2-984dca0a
% echo $?            
0
```

**Comment by Cafe137** [comment]
This is fixed in #152
