### ISSUE TITLE
Progress bar on upload to Bee client

### ISSUE THREAD

**Issue by nugaon** [ethersphere/swarm-cli#16]
We have already a progress bar on upload, but only for the data to be synced on the network.
Would be nice to have a progress bar before that to track the progress of sending the file to the Bee-client.

**Comment by Cafe137** [comment]
Some early findings: [onUploadProgress works only in the browser](https://github.com/axios/axios/issues/1966), and [progress-stream](https://www.npmjs.com/package/progress-stream) gives inaccurate results since axios reads from it faster than it actually sends over the network.

**Comment by Cafe137** [comment]
### Progress-Stream Test Results

Tested with a 160MB binary.

Axios consumed the stream within 722 ms (and in 7 parts).

Actual upload took 134,429 ms.

Looks like there is no easy way around this with Axios.

As an alternative enhancement I suggest using a simple spinner, and displaying the file size beforehand. Maybe also a broad estimation, eg. <10MB: a few seconds, <100MB a few minutes.

Monkey patching Axios could still be an option, but that sounds like going down a rabbit hole.

Details:

```
Progress event after 106 ms
{
  percentage: 8.6328125,
  transferred: 14483456,
  length: 167772160,
  remaining: 153288704,
  eta: 11,
  runtime: 0,
  delta: 14483456,
  speed: 14483456
}
Progress event after 239 ms
{
  percentage: 13.789062499999998,
  transferred: 23134208,
  length: 167772160,
  remaining: 144637952,
  eta: 6,
  runtime: 0,
  delta: 8650752,
  speed: 23134208
}
Progress event after 339 ms
{
  percentage: 27.578124999999996,
  transferred: 46268416,
  length: 167772160,
  remaining: 121503744,
  eta: 3,
  runtime: 0,
  delta: 23134208,
  speed: 46268416
}
Progress event after 439 ms
{
  percentage: 49.453125,
  transferred: 82968576,
  length: 167772160,
  remaining: 84803584,
  eta: 1,
  runtime: 0,
  delta: 36700160,
  speed: 82968576
}
Progress event after 539 ms
{
  percentage: 67.5390625,
  transferred: 113311744,
  length: 167772160,
  remaining: 54460416,
  eta: 0,
  runtime: 0,
  delta: 30343168,
  speed: 113311744
}
Progress event after 639 ms
{
  percentage: 86.328125,
  transferred: 144834560,
  length: 167772160,
  remaining: 22937600,
  eta: 0,
  runtime: 0,
  delta: 31522816,
  speed: 144834560
}
Progress event after 722 ms
{
  percentage: 100,
  transferred: 167772160,
  length: 167772160,
  remaining: 0,
  eta: 0,
  runtime: 0,
  delta: 22937600,
  speed: 134217728
}
Uploaded in 134429 ms
```

**Comment by vojtechsimetka** [comment]
Interesting. I seem to remember similar issues. My gut feeling is telling me we are doing something wrong (either on the JS or on the GO side), surely if Axios could not handle the upload progress correctly somebody would notice and fix it.

Out of curiosity try some other library like `ky` to see if the upload progress works there?

**Comment by Cafe137** [comment]
Cannot be implemented with axios. We added a spinner for intermediate resolution.
