### ISSUE TITLE
Docker command

### ISSUE THREAD

**Issue by nugaon** [ethersphere/swarm-cli#17]
There is a need for having a functionality to easily setup Bee node(s).
On every Bee realease, a `Docker` version is also available, so we could use that to pull any arbitrary version of Bee without any extra installed large dependency, and run that with the appropriate options.
Also we could use it for other Swarm JS project tests like for [bee-js](https://github.com/ethersphere/bee-js), where [a bash script helps to solve this problem currently](https://github.com/ethersphere/bee-js/blob/master/test/bee.sh).
The docker setup should be able to use templates as well, which would load from configuration (which also should be placed in other file, not in `config.json`, as it only utilized in case of `docker` subcommands). One of the default template could be the former mentioned setup that the bee-js' script using, other is connecting a single node to the main Swarm network with full configuration.

**Comment by Eknir** [comment]
If you are intending to release this to users (and not just as a dev-tool), then it would be great if you could also add bee-clef. See https://github.com/ethersphere/bee/tree/master/packaging/docker

Main reason to have bee-clef is because it enhances the security, but for users who want to earn qBZZ's, bee-clef is currently the only ways to get the keys out of Swarm, into Metamask (which will be needed)

**Comment by nugaon** [comment]
> If you are intending to release this to users (and not just as a dev-tool), then it would be great if you could also add bee-cle

Yes, this is exactly that I meant by connecting a single node with full configuration.
I would keep the docker compose yaml format for templates and rather not figure out something new, and these could be stored in CLI's config folder `docker`.

The solution of course has to be cross-platform solution, ideally the commands should communicate directly with the [Docker's API EPs](https://docs.docker.com/engine/api/)

This `swarm-cli docker (...)` command should not only start and stop Swarm environments, would be nice to interact with its services on demand, for instance like in the mentioned use-case of @Eknir, export keys from clef.

I can imagine the callable commands somehow like this:
* `swarm-cli docker template import <source>` # simple copy-paste from file or even from URL to the config folder place
* `swarm-cli docker template list` # list of the currently imported configurations
* `swarm-cli docker template remove [name]` # remove template same manner as `identity` has now
* `swarm-cli docker start [template-name]` # if no template-name has been given, it starts a full-featured Bee client (with clef)
* `swarm-cli docker list` - print containers only started by swarm-cli with some info (should be think about this particularly at the neccessary [metadata design](https://docs.docker.com/config/labels-custom-metadata/))
* `swarm-cli docker stop [template-name]` # stop Swarm environment if it has not started in attached mode
* `swarm-cli docker exec <action> [template-name]` # perform predefined common actions against Swarm environment, like export key from clef.

Of course, any other idea can be added or feel free to amend this proposal.
