### ISSUE TITLE
readme: please describe how to run without npm link

### ISSUE THREAD

**Issue by attila-lendvai** [ethersphere/swarm-cli#171]
i'm trying out `swarm-cli` on NixOS, where `npm link` fails:

```
$ npm link
npm ERR! code EROFS
npm ERR! syscall mkdir
npm ERR! path /nix/store/cdalbhzm3z4gz07wyg89maprdbjc4yah-nodejs-14.17.0/lib/node_modules/@ethersphere
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, mkdir '/nix/store/cdalbhzm3z4gz07wyg89maprdbjc4yah-nodejs-14.17.0/lib/node_modules/@ethersphere'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
```

on NixOS the directory is read only.

is there a way to run swarm-cli directly from the checked out git directory after `npm run compile`, but without `npm link`?

meanwhile i'm also working on a PR to update the readme, so either answer here, or extend the readme.

thank you!

**Comment by Cafe137** [comment]
Perhaps `node dist/index.js` works from the project root.

**Comment by attila-lendvai** [comment]
> Perhaps `node dist/index.js` works from the project root.

that indeed works, thank you!

**Comment by attila-lendvai** [comment]
FTR, i have opened a PR that adds this to the readme: https://github.com/ethersphere/swarm-cli/pull/175
