### ISSUE TITLE
Feature idea: buying stamp in verbose mode could print more information

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#205]
When buying a stamp the CLI prints the `Stamp ID`. 
```
% node dist/index.js stamp buy --depth 20 --amount 100K
Stamp ID: d158d7ab199afd048f0bdf0f0b2d08d6ecdeb2294ca23a0fa22d99c965304bf4
```

When buying a stamp in verbose mode the same information is printed out. It would be good if it printed the detailed information that it prints when showing a stamp. Something like this:

```
% node dist/index.js stamp buy --depth 20 --amount 100K -v
Stamp ID: d158d7ab199afd048f0bdf0f0b2d08d6ecdeb2294ca23a0fa22d99c965304bf4
Usage: 0%
Depth: 20
Bucket Depth: 16
Amount: 100000
Usable: true
Utilization: 0
Block Number: 9592
Immutable Flag: false
```

**Comment by Cafe137** [comment]
This information is not immediately available after buying the stamp.

Either a retry mechanism or a calculated sleep needs to be added to ensure this information is retrievable and fault tolerant.

Error is: `get stamp issuer: get issuer`

I think first we should understand better why the sleep is necessary.

**Comment by agazso** [comment]
> This information is not immediately available after buying the stamp.
> 
> Either a retry mechanism or a calculated sleep needs to be added to ensure this information is retrievable and fault tolerant.
> 
> Error is: `get stamp issuer: get issuer`
> 
> I think first we should understand better why the sleep is necessary.

Hmm, that's right. There is a waiting period after buying a postage stamp to make sure other nodes are aware of it. The `usable` property can be used to check if the postage stamp is considered valid. What do you think of adding something like a `--wait-usable` flag to the `buy` command to show a spinner until the `usable` changes to true?
