### ISSUE TITLE
Manifest command

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#234]
It would be good to have a `manifest` command for working with manifests. I imagine it could have the following subcommands:

- `list <reference>[path]` lists the content of a manifest. The reference could optionally include a path as well, in that case the subfolder is listed.
- `add <reference> <local-path>` (or `upload`?) upload a file or folder to an existing manifest, returns the hash of the updated manifest
- `get <reference>[path]` (or `download`?) downloads a file or folder from an existing manifest, if no path provided download the index-document or the whole manifest
- `del <reference><path>` (or `remove`, `rm`?) deletes a file or folder from an existing manifest, returns the hash of the updated manifest
- `merge <reference1> <reference2>` merges two references (see the conflict resolution later)
- `sync <reference1> <local-path>` synchronizes a local folder with a manifest. Useful when you want to update your website and you just want to upload the changes.

The first four is the basic functionality, the `merge` and `sync` are more advanced use-cases that would be not necessary to do in the first iteration. Theoretically those can be implemented with the first four commands, so they are mostly optimizations and convenience functions.

Also with `merge` and `sync` there is a question of *conflict resolution*: what should happen if both have resources with the same path. I imagine that we could have options to control the conflict resolution strategy (always keep from the first, etc.).

**Comment by ldeffenb** [comment]
I have implemented much of this functionality in a custom TypeScript program for my OpenStreetMap uploading efforts using mantaray-js.  I opened two issues in that repository related to improper (as in, not like the golang bee client) handling of collection-level metadata (website-index-document and website-error-document).

I am now encountering issues when trying to upload a very large (22GB) dataset.  I'm currently trying to develop a work-around that will uploading subdirectory trees individually and need the "merge" option mentioned above to put the final root mantaray node above the (hopefully by then existing) sub-collections.  Do you know if "merge" is in mantaray-js?  I didn't see it there...

**Comment by agazso** [comment]
> I am now encountering issues when trying to upload a very large (22GB) dataset. I'm currently trying to develop a work-around that will uploading subdirectory trees individually and need the "merge" option mentioned above to put the final root mantaray node above the (hopefully by then existing) sub-collections. Do you know if "merge" is in mantaray-js? I didn't see it there...

I don't know of merge functionality in mantaray-js, maybe @nugaon ?
However I imagine that it's possible to iterate through both trees and creating a new tree with the elements from both.

**Comment by ldeffenb** [comment]
I have 23,147,840 tiles across 96,679 folders 20 (zoom levels) of which are in the root.  node.js with mantaray-js cannot (currently) handle this number of nodes in RAM at once.  It grows to 4+GB virtual and then JavaScript heap is exhausted (yes, it's a 64bit node.js).  I cannot even load levels 11 or 12 directly, they individually cause the problem.

I just need a way to add a fork as a sub-path where the reference is not considered a value entry, but an edge entry.  As soon as I get another moment, I'll be attempting another manual node construction to see if I can connect these subtrees under a single node without actually loading the entire subtrees first.  And of course, still allowing the newly constructed structure to actually save, which should be straightforward by have the reference already present in the subtree node.

**Comment by nugaon** [comment]
> I don't know of merge functionality in mantaray-js, maybe @nugaon ?

There is no such a functionality yet, but it is on the table to design/implement that.
Also, the filesystem-like utility functions should be exposed from `mantaray-js` as well until then I would wait with this task.

Regarding to the `merge` conflict resolution, here is a quote from BOS:
> Updating here means all the new paths are merged with the paths of the existing manifest. In case of identical paths, the entry coming from the upload replaces the old entry.

@ldeffenb the semi-load of manifests can be sorted out, please create issue about it if it is your need in `mantaray-js` repository. also PRs are welcome.

regarding to the `add` command the `<manifest-path>` is missing as `<local-path>` can be a full-path as well.

The `get` command could be a first level command as `download` next to the `upload` functionality.

All commands also should handle metadata on files but we should elaborate the underlying logic more on `merge` and `sync` before start.

**Comment by Cafe137** [comment]
@agazso To me it seems the `get` or `download` command shares the functionality with a top-level `download` command.

I welcome this addition, but it feels a bit "hidden", as I would expect a straightforward `download` command to exist next to `upload`.

Do you think it would make sense to duplicate this command, and have it both as `download` and `manifest get`? Code wise there would be no duplication of course.

**Comment by agazso** [comment]
> @agazso To me it seems the `get` or `download` command shares the functionality with a top-level `download` command.
> 
> I welcome this addition, but it feels a bit "hidden", as I would expect a straightforward `download` command to exist next to `upload`.
> 
> Do you think it would make sense to duplicate this command, and have it both as `download` and `manifest get`? Code wise there would be no duplication of course.

I think it would be a good idea to add something like this, but I also see potential problems. The issue is that with Swarm in general the reference can point to any type of object (currently chunk, file, manifest, feed). With the manifest command we can assume that the reference is a manifest and display an error if it is not but it's not that clear what should do a general download command, what are the possible options for the different type of objects and how the options can be verified if the data is not known before downloading.

This is why I suggest to first add the `manifest get` and then we can figure out how to generalise it.
