### ISSUE TITLE
Default verbosity level

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#26]
By default there is a lot of information printed on the console. It would be better to change the default verbosity level to 1 to keep it a bit down. Then if someone needs more information (for example when debugging) they can always set the verbosity level higher.

**Comment by nugaon** [comment]
Personally I think that the verbose version should be kept default because it continuously informs the user what is happening which is always good.

**Comment by AuHau** [comment]
I would argue that the common approach to this from pretty all CLI applications and especially UNIX utilities are that you output only "the results" and have flags like `-v` to enable more details. This is especially important if you want to use it in some scripts and use piping to other commands. From this perspective it would be good to also have flag like `--no-color` or something like that, that would strip the colors chars from the stdout, but I guess it is not as critical.

I can imagine use cases like `swarm-cli upload /some/dir | mail attila@ethswarm.org` which won't be possible if you can't get only the resulting hash.

**Comment by nugaon** [comment]
for that to set verbosity to 0 would be the way to do, because provide totally silent option is non-sense.
on upload verbosity 0 currently gives back the uploaded hash of the content, but unfortunately it also prints the progress bar which ruins this behaviour and it is not intended to be like this.

**Comment by significance** [comment]
+1 for automated use

there is also the example of `curl` which is semi-verbose as default but has a `-s` option for automated use

**Comment by significance** [comment]
another perhaps pertinent consideration could be how errors are communicated to the caller in bash, so that we can e.g. retry if upload fails when used in shell scripting

**Comment by nugaon** [comment]
> another perhaps pertinent consideration could be how errors are communicated to the caller in bash

In case of errors it exits from the application with code `1` everytime. 
If some unexcepted calling format has been given, we print the manual of the command which went wrong and the error message in the last row.
Other case, when the `run()` method fails we print an error message with red colors, maybe with some info at the end, which depends from the verbosity level. It also throws `1` error code, that the CLI can react (you can try out by calling `swarm-cli upload some/folder/path && echo 'successful run'`.

**Comment by nugaon** [comment]
> another perhaps pertinent consideration could be how errors are communicated to the caller in bash

In case of errors it exits from the application with code `1` every time. 
If some unexpected calling format has been given, we print the manual of the command which went wrong and the error message in the last row.
The Other case, when the `run()` method fails we print an error message with red colors, maybe with some info at the end, which depends on the verbosity level. It also throws `1` error code, that the CLI can react on (you can try out by calling `swarm-cli upload some/folder/path && echo 'successful run'`.

**Comment by nugaon** [comment]
> there is also the example of curl which is semi-verbose as default but has a -s option for automated use

as I mentioned in my comment https://github.com/ethersphere/swarm-cli/issues/26#issuecomment-793636605 verbosity 0 is for automated usage. nevertheless if it is not intuitive for most of the users, we can introduce an alias for `-v 0`.

**Comment by agazso** [comment]
In many CLI tools I worked with there was a `-q` or `--quiet` option for minimal output and the `-v` or `--verbose` option for the verbose output. We can adopt that.

**Comment by agazso** [comment]
The original issue about default verbosity is fixed, follow the discussion about the new options in #54
