### ISSUE TITLE
Cashout command

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#27]
Currently users are using a [bash script](https://gist.github.com/ralph-pichler/3b5ccd7a5c5cd0500e6428752b37e975#file-cashout-sh) to cash out.

The CLI could also provide this functionality and it can be better maintained than a shell script on the long run. Also this would solve the [issue that running shell script on Windows](https://github.com/ethersphere/bee/issues/1092) is not trivial.

Currently the script has three subcommands:
- `cashout <peer>`: cashes out the cheques from a single peer
- `cashout-all <min-amount>`: cashes out all the cheques that reaches a minimum amount
- `list-uncashed`: list all uncashed cheques

**Comment by agazso** [comment]
I was thinking that the actual commands could be the following:

```
cashout peer <peer-id> [min-amount]: cashes out cheques from a single peer
cashout all <min-amount>: cashes out all the cheques that reaches a minimum amount
cashout list: list all uncashed cheques
```

However when thinking further about adding `deposit` and `withdraw` commands then maybe it's better to structure it otherwise. I thought about calling the command `chequebook` but [we have proof](https://github.com/ethersphere/bee-js/issues/183) that it's hard to write correctly, although it could be also possible to use `cb` as a shorter form. Then the command names could change back to `cashout-peer`, `cashout` and `list-uncashed`.

Another idea was using `bzz` for this command name because we are ultimately dealing with BZZ but that may be also confusing because it's also an overloaded concept since it's used in the endpoint and a future protocol as well.

What do you think?
@Cafe137 @nugaon @vojtechsimetka @AuHau

**Comment by nugaon** [comment]
> Another idea was using `bzz` for this command name because we are ultimately dealing with BZZ but that may be also confusing because it's also an overloaded concept since it's used in the endpoint and a future protocol as well.

I aggree with this we shouldn't use `bzz` for this too.

> However when thinking further about adding `deposit` and `withdraw` commands then maybe it's better to structure it otherwise. I thought about calling the command `chequebook` but [we have proof](https://github.com/ethersphere/bee-js/issues/183) that it's hard to write correctly, although it could be also possible to use `cb` as a shorter form. 

Good consideration, I think we definitely should group these commands under the corresponding phrases that Swarm termonology use, thereby also make these terms familiar and friendly for the users.
But even more important can be these operations have common properties like using blockchain. If the commands have the same parent command then the neccessary options and base functions can be defined there.  

> Then the command names could change back to `cashout-peer`, `cashout` and `list-uncashed`.

I guess you want to change it because the command call tree would be too long, but I would not afraid from this too much and it also keeps the concept of the above mentioned principle, so we may leave it as it is, just put an other level `cb` before `cacheout`.

**Comment by AuHau** [comment]
Hmm, is there an issue for the `deposit` and `withdraw` commands? I am not completely sure about the functionality.

I agree with following of the terminology that is used across the whole ecosystem, so I would go with `chequebook` root command. Btw. yargs supports [`recommendCommands()`](http://yargs.js.org/docs/#api-reference-recommendcommands) (see how it is used [here](http://yargs.js.org/2016/08/14/yargs-5.html)), that might also help with the bad spelling.

Honestly, I don't think we need three separate sub-commands for these tasks. I think one subcommand `cashout` with multiple flags would be sufficient. I imagine following schema:

```
cashout [--dry-run] [--peer ADDRESS] [--min AMOUNT]
```

Where by default it cash out all the cheques that exceed default min. value. If specified `--peer` then only for given address the cheque is cashed out. If `--dry-run` (or `--list` if you would like) is specified then it would show what cheques would be cashed out without cashing them.

**Comment by Cafe137** [comment]
With the `swarm-cli 0.6.0` release we have added these commands:

```
cheque cashout --all
cheque cashout --peer <peer>
cheque list
cheque deposit <amount>
cheque withdraw <amount>
```
