### ISSUE TITLE
Cannot install as root

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/swarm-cli#339]
```
root@vmi791915:~# nvm install 16
Downloading and installing node v16.14.0...
Downloading https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.xz...
######################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.14.0 (npm v8.3.1)
Creating default alias: default -> 16 (-> v16.14.0)
root@vmi791915:~# npm i -g @ethersphere/swarm-cli
npm notice 
npm notice New minor version of npm available! 8.3.1 -> 8.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.0
npm notice Run npm install -g npm@8.5.0 to update!
npm notice 
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.14.0/lib/node_modules/@ethersphere/swarm-cli/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! sh: 1: node-gyp-build: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-15T19_24_01_989Z-debug-0.log
```

**Comment by jusonalien** [comment]
hey, i have try using , and it works:)

**try using the older node version** 

~# nvm install 13
Downloading and installing node v13.14.0...
Downloading https://nodejs.org/dist/v13.14.0/node-v13.14.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v13.14.0 (npm v6.14.4)


~]# npm install --global @ethersphere/swarm-cli
/root/.nvm/versions/node/v13.14.0/bin/swarm-cli -> /root/.nvm/versions/node/v13.14.0/lib/node_modules/@ethersphere/swarm-cli/dist/index.js

> bufferutil@4.0.6 install /root/.nvm/versions/node/v13.14.0/lib/node_modules/@ethersphere/swarm-cli/node_modules/bufferutil
> node-gyp-build


> secp256k1@4.0.3 install /root/.nvm/versions/node/v13.14.0/lib/node_modules/@ethersphere/swarm-cli/node_modules/secp256k1
> node-gyp-build || exit 0


> utf-8-validate@5.0.8 install /root/.nvm/versions/node/v13.14.0/lib/node_modules/@ethersphere/swarm-cli/node_modules/utf-8-validate
> node-gyp-build


> keccak@3.0.2 install /root/.nvm/versions/node/v13.14.0/lib/node_modules/@ethersphere/swarm-cli/node_modules/keccak
> node-gyp-build || exit 0

npm WARN notsup Unsupported engine for get-random-values@1.2.2: wanted: {"node":"10 || 12 || >=14"} (current: {"node":"13.14.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: get-random-values@1.2.2

+ @ethersphere/swarm-cli@1.10.0
added 143 packages from 196 contributors in 5.479s

**Comment by Cafe137** [comment]
Solved this in bee-js, should work now
