### ISSUE TITLE
Feature Request: Tags or Descriptions for Stamps

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#342]
It is hard to keep track of which stamps were used for what. When buying stamps, it would be good to be able to specify a tag or description so that when listing the stamps they are displayed with some context.

**Comment by AuHau** [comment]
This is already part of Bee that allows to label the stamps. You can even label it using the `swarm-cli stamp buy --label "your label"` but you are right the labels are not displayed in the stamps list 😅

**Comment by significance** [comment]
awesome ❤️
