### ISSUE TITLE
feature request: show all relevant balances

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#347]
- [ ] wallet bzz balance
- [ ] wallet xdai balance
- [ ] chequebook bzz balance
- [ ] uncashed cheque bzz balance

**Comment by agazso** [comment]
One way to do this is to Bee implement such endpoints. I opened an issue about this in the Bee repo:
https://github.com/ethersphere/bee/issues/2815

**Comment by significance** [comment]
> One way to do this is to Bee implement such endpoints. I opened an issue about this in the Bee repo: [ethersphere/bee#2815](https://github.com/ethersphere/bee/issues/2815)

while i agree much of this functionality should be in Bee itself, this may also be a good candidate for one of the many things we are rapid prototyping using common garden javascript for the meantime 😀

**Comment by Cafe137** [comment]
```
 wallet bzz balance
 wallet xdai balance
 chequebook bzz balance
```

`swarm-cli balance`

---

```
 uncashed cheque bzz balance
```

`swarm-cli cheque list`
