### ISSUE TITLE
feat: show TTL in human readable format

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#355]
TTL: 11145595/60/60/24/7 seconds 😭

**Comment by Cafe137** [comment]
The `swarm-cli stamp list` and `swarm-cli stamp show` commands print `TTL: 7231860 seconds`.

We have a `printStamp` function in `src/service/stamp/index.ts` which could be enhanced to convert this value to more comprehensible units.

**Comment by agazso** [comment]
Closed by #395
