### ISSUE TITLE
swarm-cli does not work with Bee running in gateway node

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#36]
this means that it is necessary to run one's own node.

it would be great if swarm-cli could work with a remote gateway, eg. gateway.ethswarm.org

**Comment by agazso** [comment]
It seems that the reason is that swarm-cli is using tags functionality to track the progress of the upload and that is not available on gateways.

One idea to do work around this limitation is to only use tags on localhost and not on other domains unless the user specifies.

**Comment by significance** [comment]
yes, i think it could be worth using this to open the discussion on enabling tags in gateway mode by otherwise mitigating potential attack vectors. it's a very important feature I think.

**Comment by agazso** [comment]
Relevant issue: https://github.com/ethersphere/bee/issues/1369

**Comment by Cafe137** [comment]
It is now possible to upload to gateway using the `--skip-sync` flag
