### ISSUE TITLE
ux: why is my data too big?

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#363]
![Screenshot 2022-04-09 at 14 48 07](https://user-images.githubusercontent.com/130104/162577037-15645fec-2ed0-44a4-8a6a-0f12528c9c15.png)

is it due to the stamp or just because swarm network?

**Comment by significance** [comment]
![Screenshot 2022-04-09 at 14 49 13](https://user-images.githubusercontent.com/130104/162577073-2b6c5a81-0271-493a-8ac7-f6dc9acf662a.png)

aha!

**Comment by significance** [comment]
we should be more descriptive perhaps? or is it a warning we should dispense with now

**Comment by Cafe137** [comment]
This is a warning related to the supported data size as of milestone 1.
Completing milestone 4 would elevate or completely lift this warning.
