### ISSUE TITLE
fix: it's not needed to create a new manifest to read a feed

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#372]
it's not needed to create a new manifest in order to read a feed - just fetch and decode the old one

in this case it is not needed to provide a stamp in order to read the feed

```
    if (!this.stamp) {
      this.stamp = await pickStamp(this.beeDebug, this.console)
    }

    const manifest = await this.bee.createFeedManifest(this.stamp, 'sequence', topic, addressString)
```

**Comment by Cafe137** [comment]
Duplicate of https://github.com/ethersphere/swarm-cli/issues/123
