### ISSUE TITLE
feat: predict how much a stamp will cost

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#380]
it would be great to know how much a stamp will cost, before buying it.

**Comment by Cafe137** [comment]
When buying a stamp with the `swarm-cli stamp buy` command, the `amount` and `depth` are required fields which are passed by the user. These are used in the formula for calculating the postage batch price.

Calculate and print this BZZ cost, which is already implemented in Bee Dashboard and can be copied here: https://github.com/ethersphere/bee-dashboard/blob/master/src/utils/index.ts#L218

When running without the `--yes` flag, prompt the user if they want to continue the purchase with the given price.
