### ISSUE TITLE
Upload summary readability improvements

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#405]
After uploading data there is a summary which contains lot of information and some of them are not easily readable by humans. For example I have an output that looks like this:

```
% swarm-cli upload test                                                                      
Swarm hash: ca36625b570bb3c33c0a2b3d65123f52353c964a91a52bb1b525b0c6490b3bfa
URL: http://localhost:1633/bzz/ca36625b570bb3c33c0a2b3d65123f52353c964a91a52bb1b525b0c6490b3bfa/
Bzz.link: https://bah5acgzazi3gew2xboz4gpakfm6wker7ki2tzfsksgssxmnvewymmsilhp5a.bzz.link
Stamp ID: 0f49cad16a8224ba4cd1b3362c6cc1cdccca8cdfa56688344e3c44eb384d976c
Label: recovered
Usage: 35%
TTL: 2310780 seconds
```

Now we cannot do anything about the `Swarm hash`, `URL` and `Bzz.link` fields, because they contain the minimum necessary information already.

However I see two possible improvements. The `Stamp ID` could be shortened to the first 8 characters (just like git does with the commit hashes) and in the unlikely case that it's ambiguous then print more. Also the `TTL` field could be printed in human readable format using the same code as in https://github.com/ethersphere/swarm-cli/pull/403.

**Comment by Cafe137** [comment]
Another point: do not print the Label if it is empty
