### ISSUE TITLE
it would be difficult to discern the relevant information when using the tool with automation

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#41]
it would be useful if important hashes are able to be parsed by automation, eg. github actions

**Comment by agazso** [comment]
See another relevant discussion going on about this: https://github.com/ethersphere/swarm-cli/issues/26

The idea is that you can change the verbosity with the `-v` option. For automation I suggest to try `-v 0` which reduces the output verbosity to minimal and usually it only prints a single hash as the output of an operation.

You can already try it in this branch: https://github.com/ethersphere/swarm-cli/pull/32

**Comment by significance** [comment]
cool, let's continue there 😀
