### ISSUE TITLE
balance is NaN

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#435]
ubuntu / node 14 /  Bee 1.10.0

![Screenshot 2022-12-21 at 08 08 41](https://user-images.githubusercontent.com/130104/208853029-7ae92bfb-a371-44e7-923c-701ecc2d8031.png)
![Screenshot 2022-12-21 at 08 07 15](https://user-images.githubusercontent.com/130104/208853045-b28066ef-5a73-4956-8c03-2b873697bc95.png)

**Comment by AuHau** [comment]
Yeah that is most probably because of the breaking changes in the wallet EP. Will need to update bee-js to fix this.

**Comment by solo12zw74** [comment]
Hello @AuHau Is it planned to do? Or this issue opened for contributions?
