### ISSUE TITLE
Trying to upload a file and getting false == true error

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/swarm-cli#438]
Trying to upload a file (caa. 800MB) via swarm-cli returns an error, see screenshot:

![image](https://user-images.githubusercontent.com/1554520/213641819-b4631023-f60e-404b-ae12-359ed98d0904.png)

This happens quite quickly after confirming, probably the upload does not even start.

Expected behavior: a more descriptive error message returned.

**Comment by rampall** [comment]
I get the same error in bee dev mode (macbook) on any file upload
<img width="598" alt="image" src="https://user-images.githubusercontent.com/520570/224665636-f68abfe4-7b28-4afc-8310-a50b790b991b.png">

**Comment by rampall** [comment]
downgrading node version from 18 to 16 fixed this for me
