### ISSUE TITLE
Feature - Dry run Upload with CLI

### ISSUE THREAD

**Issue by n00b21337** [ethersphere/swarm-cli#441]
Think it would be a nice addition to have the dry run option on swarm-cli upload, just to get the hash of the file(s) we want to upload. This could be helpful for verifying what is what. IPFS has similar thing and I found it useful when I want to check if a directory is the one I already stored. If I am not mistaken currently I need to reupload in swarm which is kind of bad UX for that.

**Comment by Cafe137** [comment]
Tracking in https://github.com/ethersphere/swarm-cli/issues/439
