### ISSUE TITLE
Getting BAD REQUEST when using swarm-cli  feed upload -T

### ISSUE THREAD

**Issue by kmetaprovide** [ethersphere/swarm-cli#497]
root@pixel:/home/ansible/backup-solution-for-nc/swarm-up# swarm-cli  feed upload -T ramesh_nc backup_pixel_nextcloud_2023-11-30_10-17-14.tar.gz-part-012-of-100 --verbose
? Please select a stamp for this action 
cad20fadbfed3e825f2598f21b02e841a3a4565699d8027906dd38f39d6cd086 127.76 GB expires in 
Upload size is approximately 8.43 MB
Data has been sent to the Bee node successfully!
Swarm hash: 726efcbb86c2b2d59edb98a23c9493aebbcf8083640f801b855608bda4db4e7d
Waiting for file chunks to be synced on Swarm network...
Uploading was successful!
URL: http://localhost:1633/bzz/726efcbb86c2b2d59edb98a23c9493aebbcf8083640f801b855608bda4db4e7d/
ERROR Bad Request

**Comment by kmetaprovide** [comment]
running bee dev

**Comment by Cafe137** [comment]
I believe SOCs are no longer supported in `bee dev` mode, please see https://github.com/ethersphere/bee/issues/4652

Do you have this issue on testnet or mainnet?

**Comment by Cafe137** [comment]
Please reopen if this issue happens outside of `dev` mode.
