### ISSUE TITLE
feature request: pin in retrospect

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#59]
it would be useful to be able to pin chunks and their children, that are already existent in the network.

eg. `swarm-cli pin eba7925a4d82c33affaf95fbf3885096487ceb27d8c9f1601f73db4f8ec7624a`

**Comment by Cafe137** [comment]
With the `0.6.0` release we have added 3 commands:

```
pinning pin
pinning unpin
pinning list
```
