### ISSUE TITLE
swarm-cli tries to sync even if Bee is running in standalone mode

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#61]
this doesn't make sense! 🤔 

```
Waiting for file chunks to be synced on Swarm network...
 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 99% | ETA: INFs | 2014/202074fee8cc9dbac82a954f907d15a454337f8713286af090166ab8a715ec07c02b
Data syncing timeout.
```

**Comment by agazso** [comment]
How about we add a `--no-sync` flag to the `upload` and `feed upload` commands? It would also serve as a workaround for this and #36.

**Comment by significance** [comment]
yeah i think it's worthwhile. would be good to continue the conversation about allowing tags at the gateway too.
