### ISSUE TITLE
swarm-cli upload only gives back hash

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#62]
not the entire url, as the feeds endpoint does

having the whole url including the gateway enables a much better user experience

**Comment by agazso** [comment]
Can you please provide an example what you mean exactly?

What I see is that in quiet mode (`-q` or `-v 0` in older versions) it only prints the hash, but in the default verbosity and verbose mode it prints the whole url. Is that what you suggest to change?

**Comment by significance** [comment]
yes you are right, it's there in the latest version! cheers 😁
