### ISSUE TITLE
print feed manifest hash without doing update

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-cli#63]
it would be useful to be able to retrieve a feed manifest hash/url without having to do an update

perhaps a ux variant or additional feature request would be to not update the feed if the current latest feed update matches the upload hash (i.e. the user has attempted to upload the same content as an updated)

**Comment by agazso** [comment]
Have you tried the `feed print` command? It seems to be doing exactly what you are asking for:

```
 % swarm-cli feed print -i main -P 1   
Feed Manifest URL -> http://localhost:1633/bzz/fdf21a5556e968c4079ba6b06b16a6ec545c2ce189db867c0ad5f6a0d4004de6/

 % swarm-cli feed print -i main -P 1 -v
Chunk Reference -> 1868f182f46306f709ebc02271cea4776a1d45510e7bce3607be7d302b3cf2d7
Chunk Reference URL -> http://localhost:1633/files/1868f182f46306f709ebc02271cea4776a1d45510e7bce3607be7d302b3cf2d7
Feed Index -> 0000000000000008
Next Index -> 0000000000000009
Feed Manifest -> fdf21a5556e968c4079ba6b06b16a6ec545c2ce189db867c0ad5f6a0d4004de6
Feed Manifest URL -> http://localhost:1633/bzz/fdf21a5556e968c4079ba6b06b16a6ec545c2ce189db867c0ad5f6a0d4004de6/
```

**Comment by agazso** [comment]
> perhaps a ux variant or additional feature request would be to not update the feed if the current latest feed update matches the upload hash (i.e. the user has attempted to upload the same content as an updated)

Great idea, I created a new issue for that: https://github.com/ethersphere/swarm-cli/issues/64

**Comment by significance** [comment]
perfect! thanks! 😁
