### ISSUE TITLE
Error when using recursive (-r) option 

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#7]
I was trying to use the `recursive` option to upload a directory to Bee and I get an error (see below). Interestingly if I am not using the `recursive` option the upload of a directory is still successful.

```
~/Projects/swarm-cli (feat/identity*) % node dist/index.js upload -r ../swarm-cli/dist                                 
index.js upload <path>

- Upload file to Swarm

Positionals:
  path  Path of the file (even directory)                             [required]

Options:
      --help                Show help                                  [boolean]
      --version             Show version number                        [boolean]
      --bee-api-url         URL of the Bee-client API
                                     [string] [default: "http://localhost:1633"]
      --config-folder       Path of the configuration files that the CLI uses
                                                                        [string]
      --pin                 Persist the uploaded data on the gateway node
                                                                       [boolean]
  -r, --recursive           Upload directory            [string] [default: true]
      --tag-polling-time    Waiting time in ms between tag pollings
                                                         [string] [default: 500]
      --tag-polling-trials  After the given trials the tag polling will stop
                                                          [string] [default: 15]
      --index-document      Default retrieval file on bzz request without
                            provided filepath   [string] [default: "index.html"]
      --error-document      Default error file on bzz request without with wrong
                            filepath                                    [string]

Not enough non-option arguments: got 0, need at least 1
```

**Comment by nugaon** [comment]
as the help print says `upload <path>` has to be the format of the command. If you want to provide options it has to be after this formula.
In case of parent options, you can provide even before the command e.g.  `swarm-cli --bee-api-url http://localhost:11633 upload ../swarm-cli/dist  -r` or also after `swarm-cli upload ../swarm-cli/dist  -r --bee-api-url http://localhost:11633`

**Comment by agazso** [comment]
Reopening because the help says nothing about where the options are supposed to be.

It is highly unusual for CLI tools that the options can come only after the arguments. Usually it's either before the arguments (for example see `node`, `curl`, `tsc`, all unix tools, or for a similar multi-level command line tool `docker`) or the the position of the options doesn't matter (much less common, for example `npm`)
