### ISSUE TITLE
Improve general usage printing

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/swarm-cli#86]
# Improvements

- [x] Whenever groups are listed, also print this info: 

```
Run 'swarm-cli GROUP --help' to see available commands in a group
```

- [x] Whenever commands are listed, also print this info: 

```
Run 'swarm-cli COMMAND --help' for more information on a command
```

- [x] When only `swarm-cli` is called, also print a headline, eg.:

```
swarm-cli v0.6.1 - Manage your Bee node and interact with the Swarm network via the CLI
```

- [x] When only `swarm-cli` is called, do not print error message

- [x] When groups are called without commands, do not print error message

- [x] When help is printed for a specific command, include an usage part, eg.:

```
█ Usage:

swarm-cli feed upload <path> [OPTIONS]
```

- [x] When commands are called without any options and arguments BUT they require an argument, print usage instead of the error message

---

# Mockup

![image](https://user-images.githubusercontent.com/77121044/116822471-31d26380-ab7f-11eb-8e9b-f9727d8c905e.png)

**Comment by agazso** [comment]
Also it would be nice if running the command without arguments would not print an error.

**Comment by Cafe137** [comment]
@agazso I see two options.

Just removing the error message and printing like if it was called with `--help`.

Or printing a concise info on the command, something like this:

```
█ swarm-cli upload :: Upload file to Swarm

Usage: `swarm-cli upload <file> [options]`

For complete reference, see: `swarm-cli upload --help`
```

**Comment by agazso** [comment]
> @agazso I see two options.

I'm fine with both options.

**Comment by Cafe137** [comment]
@agazso I have created a checklist in the original post. Can you please approve these changes before I finish up the implementation?

@nugaon Can you please also take a look and leave feedback? Thanks!

**Comment by agazso** [comment]
> @agazso I have created a checklist in the original post. Can you please approve these changes before I finish up the implementation?

Looks good!

**Comment by Cafe137** [comment]
![image](https://user-images.githubusercontent.com/77121044/116931679-9960df80-ac61-11eb-9fd2-7bade6ef7927.png)

**Comment by Cafe137** [comment]
![image](https://user-images.githubusercontent.com/77121044/116931771-b85f7180-ac61-11eb-9fe0-93507dac4f1b.png)

**Comment by Cafe137** [comment]
## Group Scope

![image](https://user-images.githubusercontent.com/77121044/116931865-d62cd680-ac61-11eb-94c8-40f5e4e74c45.png)
